version: 2.1

job-post-steps: &job-post-steps
  post-steps:
   - slack/notify_failed

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  node: cloudify/public-unittest-orb@volatile
  wagonorb: cloudify/wagon-bulder-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  managerorb: cloudify/manager-orb@volatile
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    environment:
      PYENV_VERSION: 3.6.5
    docker:
      - image: circleci/python:3.6

commands:
  install_libvirt_dev:
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libvirt-dev

jobs:
  custom_unittest:
    environment:
      PYENV_VERSION: 3.6.5
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - install_libvirt_dev
      - node/unittests # Utilize commands in steps

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - custom_unittest
      - node/validate_version_job
      - node/validate_documentation_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|main)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|main)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|main)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|main)/
      - releaseorb/release:
          filters:
            branches:
              only: /master|main/
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
            - node/validate_version_job
            - node/validate_documentation_job
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /master|main/
          requires:
            - releaseorb/release
            - node/validate_documentation_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,1,3,5"
        filters:
          branches:
            only:
              - master|main
    jobs:
      - node/check_py3_compat_job
      - node/validate_version_job
      - custom_unittest
